#-------------Stage 1 : Build stage-----------
FROM eclipse-temurin:17-jdk AS builder

WORKDIR /app

COPY HelloWorld.java .

RUN javac HelloWorld.java 

#-------------Stage 2 : Runtime stage-----------

FROM eclipse-temurin:17-jdk AS builder

WORKDIR /app

COPY --from=builder /app/HelloWorld.class .
CMD ["java","HelloWorld"]
