# Stage 1: Build
FROM eclipse-temurin:17-jdk-alpine AS builder

WORKDIR /app
COPY HelloWorld.java .

RUN javac HelloWorld.java


# Stage 2: Runtime
FROM eclipse-temurin:17-jre-alpine

WORKDIR /app

# Create non-root user
RUN addgroup -S appgroup && adduser -S appuser -G appgroup

COPY --from=builder /app/HelloWorld.class .

USER appuser

CMD ["java","HelloWorld"]
