# Stage 1: Build
FROM eclipse-temurin:17-jdk-alpine AS builder

WORKDIR /app

# Create non-root user
RUN addgroup -S appgroup && adduser -S appuser -G appgroup

COPY HelloWorld.java .

RUN javac HelloWorld.java


# Stage 2: Runtime (Distroless)
FROM gcr.io/distroless/java17-debian11

WORKDIR /app

COPY --from=builder /app/HelloWorld.class .

# Run container as non-root user
USER 65532

CMD ["HelloWorld"]
