apiVersion: v1
kind: Pod
metadata:
    name: busybox-pod
    labels:
        app: busybox
        environment: dev
spec:
   containers:
   - name: busybox
     image: busybox
     command: ["sh", "-c", "echo Hello Dosto from the pod && sleep 3600"]
