apiVersion: v1
kind: Pod
metadata:
  name: configmap-env-demo
spec: 
  containers:
  - name: test-container
    image: busybox
    command: [ "/bin/sh", "-c"]
    args: 
     - |
       echo "APP_ENV: $APP_ENV";
       echo "APP_DEBUG: $APP_DEBUG";
       echo "APP_PORT: $APP_PORT";
       sleep 3600;
    envFrom:
    - configMapRef:
        name: app-config
