services:

  web:
    build: .
    ports:
      - "5001:5000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    restart: on-failure

    labels:
      app: "docker-3tier-demo"
      tier: "frontend"
      maintainer: "devops-demo"

  db:
    image: postgres:15
    restart: always

    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

    labels:
      app: "docker-3tier-demo"
      tier: "database"

  redis:
    image: redis:7
    restart: unless-stopped

    labels:
      app: "docker-3tier-demo"
      tier: "cache"

volumes:
  postgres_data:
