apiVersion: v1
kind: Pod
metadata:
  name: pvc-pod
spec:
  containers:
    - name: pvc-container
      image: busybox
      command: 
        - /bin/sh
        - -c
        - sleep 3600
      volumeMounts:
        - mountPath: "/data"
          name: pvc-volume
  volumes:
    - name: pvc-volume
      persistentVolumeClaim:
        claimName: hostpath-demo-claim
